In [1]:
import pandas as pd#loading the required packages
import numpy as np

In [2]:
gold_sample=pd.read_csv('../data/gold_sample.csv',index_col=0)#loading the gold sample dataset
gold_sample.head()#showing the output

,TOPIC0,TOPIC1,TOPIC2,TOPIC3,TOPIC4,TOPIC5,TOPIC6,TOPIC7,TOPIC8,TOPIC9,...,TOPIC1191,TOPIC1192,TOPIC1193,TOPIC1194,TOPIC1195,TOPIC1196,TOPIC1197,TOPIC1198,TOPIC1199,class
id,,,,,,,,,,,,,,,,,,,,,
7153,0.189778,0.028247,0.082636,0.242747,0.037713,0.145649,0.093700,-0.138572,0.131927,-0.601126,...,0.034746,0.008808,0.086159,0.073585,-0.087079,-0.124133,0.039286,0.091516,0.061185,neg
7951,0.609251,0.772423,-0.227274,0.066121,0.294486,0.554525,0.286519,0.440216,-0.375146,0.288990,...,0.020882,-0.005793,0.129757,-0.021887,0.060143,0.018680,-0.018766,-0.030351,-0.053974,neg
4026,0.909468,0.906008,0.691776,-0.394227,-0.342606,-0.101572,-0.809699,0.409908,-0.112820,0.192804,...,-0.014560,0.048796,-0.008395,-0.011385,-0.008501,0.038162,0.036982,-0.080868,-0.018973,pos
7261,0.254962,0.064148,0.186428,0.606833,0.473354,-0.550509,-0.250238,0.130667,0.076447,0.049817,...,0.004710,0.006922,0.044617,-0.023315,-0.023567,0.031834,0.028880,-0.010136,-0.047672,neg
4875,0.130645,0.002654,0.088650,0.199359,0.027583,0.225762,-0.005165,-0.105642,0.820503,0.369489,...,-0.012107,-0.044665,-0.072195,-0.052014,-0.041819,-0.022617,-0.058429,-0.019916,-0.025557,pos

In [3]:
mturk=pd.read_csv('../data/mturk.csv',index_col=0)#loading the mturk dataset

In [4]:
mturk_sample=pd.merge(gold_sample,mturk,on='id',suffixes=('','_y'))
#merging the gold sample and mturk based on id and renaming the _x duplicates as nothing and keeping _y as it is for now
mturk_sample=mturk_sample.drop([col for col in mturk_sample.columns if '_y' in col],axis=1)
#dropping all the columns which has _y in their column name so that all the duplicated columns are removed to get final sample

In [5]:
mturk_sample.to_csv('../data/mturk_sample.csv')#storing the mturk sample that has been generated in the data folder as told
mturk_sample.head()#showing the output of the mturk sample.

,TOPIC0,TOPIC1,TOPIC2,TOPIC3,TOPIC4,TOPIC5,TOPIC6,TOPIC7,TOPIC8,TOPIC9,...,TOPIC1192,TOPIC1193,TOPIC1194,TOPIC1195,TOPIC1196,TOPIC1197,TOPIC1198,TOPIC1199,class,annotator
id,,,,,,,,,,,,,,,,,,,,,
7153,0.189778,0.028247,0.082636,0.242747,0.037713,0.145649,0.0937,-0.138572,0.131927,-0.601126,...,0.008808,0.086159,0.073585,-0.087079,-0.124133,0.039286,0.091516,0.061185,neg,A207OR9LV0PAPY
7153,0.189778,0.028247,0.082636,0.242747,0.037713,0.145649,0.0937,-0.138572,0.131927,-0.601126,...,0.008808,0.086159,0.073585,-0.087079,-0.124133,0.039286,0.091516,0.061185,neg,A233ONYNWKDIYF
7153,0.189778,0.028247,0.082636,0.242747,0.037713,0.145649,0.0937,-0.138572,0.131927,-0.601126,...,0.008808,0.086159,0.073585,-0.087079,-0.124133,0.039286,0.091516,0.061185,neg,ARX0S1CIDJLOX
7153,0.189778,0.028247,0.082636,0.242747,0.037713,0.145649,0.0937,-0.138572,0.131927,-0.601126,...,0.008808,0.086159,0.073585,-0.087079,-0.124133,0.039286,0.091516,0.061185,neg,A3CFNUD7VR2E1E
7153,0.189778,0.028247,0.082636,0.242747,0.037713,0.145649,0.0937,-0.138572,0.131927,-0.601126,...,0.008808,0.086159,0.073585,-0.087079,-0.124133,0.039286,0.091516,0.061185,neg,A2TEWO3WJ5YKGG